//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIConfiguracion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HorasBecaEntities : DbContext
    {
        public HorasBecaEntities()
            : base("name=HorasBecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<BECA> BECA { get; set; }
        public virtual DbSet<BECAAE> BECAAE { get; set; }
        public virtual DbSet<BECAHATU> BECAHATU { get; set; }
        public virtual DbSet<BECAXPERIODO> BECAXPERIODO { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<ESTADOSOLICITUD> ESTADOSOLICITUD { get; set; }
        public virtual DbSet<estudiantes> estudiantes { get; set; }
        public virtual DbSet<EVALUACION> EVALUACION { get; set; }
        public virtual DbSet<MENSAJE> MENSAJE { get; set; }
        public virtual DbSet<MENSAJENUEVO> MENSAJENUEVO { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<RESPONSABLEXESTUDIANTE> RESPONSABLEXESTUDIANTE { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<SEMESTRE> SEMESTRE { get; set; }
        public virtual DbSet<sistema_informacion> sistema_informacion { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUD { get; set; }
        public virtual DbSet<TRANSACCIONES> TRANSACCIONES { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int insertarSemestre(Nullable<int> semestre, Nullable<int> ano, Nullable<System.DateTime> fechaApertura, Nullable<System.DateTime> fechaCierre)
        {
            var semestreParameter = semestre.HasValue ?
                new ObjectParameter("Semestre", semestre) :
                new ObjectParameter("Semestre", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(int));
    
            var fechaAperturaParameter = fechaApertura.HasValue ?
                new ObjectParameter("FechaApertura", fechaApertura) :
                new ObjectParameter("FechaApertura", typeof(System.DateTime));
    
            var fechaCierreParameter = fechaCierre.HasValue ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertarSemestre", semestreParameter, anoParameter, fechaAperturaParameter, fechaCierreParameter);
        }
    
        public virtual int editarSemestre(Nullable<int> id, Nullable<System.DateTime> fechaInicioEvaluacion, Nullable<System.DateTime> fechaCierreEvaluacion, Nullable<System.DateTime> fechaTrabajoSocial)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fechaInicioEvaluacionParameter = fechaInicioEvaluacion.HasValue ?
                new ObjectParameter("FechaInicioEvaluacion", fechaInicioEvaluacion) :
                new ObjectParameter("FechaInicioEvaluacion", typeof(System.DateTime));
    
            var fechaCierreEvaluacionParameter = fechaCierreEvaluacion.HasValue ?
                new ObjectParameter("FechaCierreEvaluacion", fechaCierreEvaluacion) :
                new ObjectParameter("FechaCierreEvaluacion", typeof(System.DateTime));
    
            var fechaTrabajoSocialParameter = fechaTrabajoSocial.HasValue ?
                new ObjectParameter("FechaTrabajoSocial", fechaTrabajoSocial) :
                new ObjectParameter("FechaTrabajoSocial", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editarSemestre", idParameter, fechaInicioEvaluacionParameter, fechaCierreEvaluacionParameter, fechaTrabajoSocialParameter);
        }
    
        public virtual int insertarPeriodo(Nullable<System.DateTime> fechaApertura, Nullable<System.DateTime> fechaCierre, string idAdministrador, Nullable<int> idSemestre, string becas)
        {
            var fechaAperturaParameter = fechaApertura.HasValue ?
                new ObjectParameter("FechaApertura", fechaApertura) :
                new ObjectParameter("FechaApertura", typeof(System.DateTime));
    
            var fechaCierreParameter = fechaCierre.HasValue ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(System.DateTime));
    
            var idAdministradorParameter = idAdministrador != null ?
                new ObjectParameter("IdAdministrador", idAdministrador) :
                new ObjectParameter("IdAdministrador", typeof(string));
    
            var idSemestreParameter = idSemestre.HasValue ?
                new ObjectParameter("IdSemestre", idSemestre) :
                new ObjectParameter("IdSemestre", typeof(int));
    
            var becasParameter = becas != null ?
                new ObjectParameter("becas", becas) :
                new ObjectParameter("becas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertarPeriodo", fechaAperturaParameter, fechaCierreParameter, idAdministradorParameter, idSemestreParameter, becasParameter);
        }
    }
}
