//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIConfiguracion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJE
    {
        public int Id { get; set; }
        public string EmailOrigen { get; set; }
        public string EmailDestino { get; set; }
        public string Tema { get; set; }
        public string Mensaje1 { get; set; }
        public int Estado { get; set; }
    
        public virtual ESTADO ESTADO1 { get; set; }
    }
}
