//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRetroalimentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEMESTRE()
        {
            this.PERIODO = new HashSet<PERIODO>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public int Id { get; set; }
        public int Semestre1 { get; set; }
        public int Ano { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public Nullable<System.DateTime> FechaTrabajoSocial { get; set; }
        public Nullable<System.DateTime> FechaInicioEvaluacion { get; set; }
        public Nullable<System.DateTime> FechaCierreEvaluacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERIODO> PERIODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
