//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIReportes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorasBecaEntities : DbContext
    {
        public HorasBecaEntities()
            : base("name=HorasBecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<BECA> BECA { get; set; }
        public virtual DbSet<BECAAE> BECAAE { get; set; }
        public virtual DbSet<BECAHATU> BECAHATU { get; set; }
        public virtual DbSet<BECAXPERIODO> BECAXPERIODO { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<ESTADOSOLICITUD> ESTADOSOLICITUD { get; set; }
        public virtual DbSet<estudiantes> estudiantes { get; set; }
        public virtual DbSet<EVALUACION> EVALUACION { get; set; }
        public virtual DbSet<MENSAJE> MENSAJE { get; set; }
        public virtual DbSet<MENSAJENUEVO> MENSAJENUEVO { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<RESPONSABLEXESTUDIANTE> RESPONSABLEXESTUDIANTE { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<SEMESTRE> SEMESTRE { get; set; }
        public virtual DbSet<sistema_informacion> sistema_informacion { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUD { get; set; }
        public virtual DbSet<TRANSACCIONES> TRANSACCIONES { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
