//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISolicitudes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BECAHATU
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Nota { get; set; }
        public string NombreResponsable { get; set; }
        public byte[] ScreenShotNota { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
